# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='in_print',
        ),
    ]
